set nocompatible " stops vim from emulating the bugs inherent in vi.
set scrolloff=2
colorscheme desert
set bg=dark
set history=1000
set title

" These two commands help format C-like source code.
set autoindent
set smartindent

set showmatch

set vb t_vb=

" This shows what your are typing as a command.
set showcmd

" Needed for Syntax Highlighting and stuff
filetype on 
filetype plugin on
syntax enable

" NB : grep will sometimes skip displyaing the file name if you search
" in a single file. Set your grep program to always generate a file name.
set grepprg=grep\ -nH\ $*

set nohls " I find it annoying that the search highlights everything it finds. This turns this off (turn it back on with :set hls).

" Useful to enforce 79 column formatting recommend for python
"set colorcolumn=80

" Spaces are better than a tab character
set tabstop=8
set expandtab
set smarttab

" Who wants an 8 character tab?
set shiftwidth=4
set softtabstop=4

" Cool tab completion stuff
set wildmenu
set wildmode=list:longest

"Line Numbers
set number

"Ignore case
set ignorecase

"Smart Case
set smartcase

" remap jj to escape in insert mode. 
inoremap jj <Esc>

nnoremap JJJJ <Nop>

" Incremental serch
set incsearch

" When I close a tab, remove the buffer
set nohidden

" Swap ; and : Convenient.
nnoremap ; :
nnoremap : ;

"Set up backup and temporary file directories
set backup 
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

" Automatically cd into the directory that the file is in
autocmd BufEnter * execute "chdir ".escape(expand("%:p:h"), ' ')

" Change some stuff for moving around buffers
map <right> :bn<cr>
map <left>  :bp<cr>

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'

" automatically save and load folders
au BufWinLeave * mkview 
au BufWinEnter * silent loadview

" Matlab highlighting
source $VIMRUNTIME/macros/matchit.vim

" mouse configuration
" set mouse=nicr

" NB : Staring with Vim 7, the filetype of emtpy .tex files defaults to 
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'

" To install solarized move solarized.vim to the vim/colors directory
"let g:solarized_termcolors = 16
"let g:solarized_visibility = "high"
"let g:solarized_contrast = "high"
se t_Co=16
colorscheme solarized

" Remove all trailing white space on save
autocmd BufWritePre * :%s/\s\+$//e
